esphome:
  name: balcony-esp

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: VERY_VERBOSE #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart

# Enable Home Assistant API
api:

ota:
  password: "d89274316948774714468e5159a94059"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Balcony-Esp Fallback Hotspot"
    password: "SUA0lKujujub"

captive_portal:

i2c:
  sda: GPIO4  
  scl: GPIO5  
  scan: false
  frequency: 100kHz
  
dallas:
 - pin: GPIO2
   update_interval: 10s
   id: balcony_street_temp

sensor:
  - platform: aht10
    id: balcony_aht10
    temperature:
      name: "Balcony Temperature"
    humidity:
      name: "Balcony Humidity"
    update_interval: 10s
    
  - platform: dallas
    address: 0xA53C01F0953D6F28
    name: "Street Temperature"
