esphome:
  name: kitchen-esp
  platform: ESP8266
  board: esp01_1m
    
  libraries:
    - ArduinoJson
    - SPI
    - Wire

  includes:
    - ../libs/Adafruit_AHT10/
    - ../libs/Adafruit_BusIO/
    - ../libs/LiquidCrystal_I2C/
    - kitchen-esp/LCD1602Display.h
    - kitchen-esp/KitchenCustomSensor.h

# Enable logging
logger:
  level: VERBOSE #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart

ota:
  password: "979f69d74d6592803c3be9f89b432f37"

wifi:
  ssid: "ASUS"
  password: "02262017"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kitchen-Esp Fallback Hotspot"
    password: "5IXTRUYdAXVH"

mqtt:
  broker: 192.168.1.187
  username: sergeyz
  password: Serg9292

captive_portal:

i2c:
  sda: GPIO4  
  scl: GPIO5  
  scan: false
  frequency: 100kHz
  
sensor:
  - platform: aht10
    temperature:
      name: "Kitchen Temperature"
    humidity:
      name: "Kitchen Humidity"
    update_interval: 10s
    
  - platform: custom
    lambda: |-
      auto kitchenMQTTSensor = new KitchenCustomSensor();
      App.register_component(kitchenMQTTSensor);
      return {kitchenMQTTSensor->ds18b20TempBalconyStreet};
      
    sensors:
    - name: "Temperature (Street-from-MQTT)"
      unit_of_measurement: °C
      accuracy_decimals: 2

