esphome:
  name: main-esp
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:
  level: VERBOSE #makes uart stream available in esphome logstream
  baud_rate: 0 #disable logging over uart

mqtt:
  broker: 192.168.1.187
  username: sergeyz
  password: Serg9292

ota:
  password: "4b770169f2f59a7e9f305942ba15c257"

wifi:
  ssid: "ASUS"
  password: "02262017"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Main-Esp Fallback Hotspot"
    password: "eEOh39GOrcCY"

captive_portal:

i2c:
  sda: GPIO4  
  scl: GPIO5  

sensor:

  - platform: bmp280
    temperature:
      name: "Hall Temperature"
      oversampling: 16x
    pressure:
      name: "Hall Pressure"
      unit_of_measurement: "mmHg"
      filters:
        - multiply: 0.750062
    update_interval: 10s
    address: 0x76
    